---

java:
  VERSION: "java-1.8.0-openjdk"

jenkins:
  repo_URL: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
  gpg_key: "https://pkg.jenkins.io/redhat-stable/jenkins.io.key"
  JAVA_OPTIONS: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"